from __future__ import annotations

"""Scatter-style plots (COP/COM XY) and their time+scatter panels."""

from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np

from . import common as _common
from .shared import as_ndarray, as_optional_ndarray, as_output_path, as_tuple_key, as_tuple_keys


def plot_cop(
    *,
    aggregated: Dict[str, np.ndarray],
    output_path: Path,
    key: Tuple[Any, ...],
    mode_name: str,
    group_fields: List[str],
    markers: Dict[str, Dict[str, float]],
    event_vlines: List[Dict[str, Any]],
    event_vline_style: Dict[str, Any],
    event_vline_order: Sequence[str],
    x_axis: Optional[np.ndarray],
    target_axis: Optional[np.ndarray],
    time_start_ms: float,
    time_end_ms: float,
    time_start_frame: Optional[float],
    time_end_frame: Optional[float],
    time_zero_frame: float = 0.0,
    device_rate: float = 1000.0,
    cop_channels: Sequence[str] = (),
    grid_layout: Optional[Sequence[int]] = None,
    cop_style: Optional[Dict[str, Any]] = None,
    common_style: Optional[Dict[str, Any]] = None,
    window_spans: Optional[List[Dict[str, Any]]] = None,
) -> None:
    _common._plot_cop(
        aggregated=aggregated,
        output_path=as_output_path(output_path),
        key=as_tuple_key(key),
        mode_name=mode_name,
        group_fields=group_fields,
        markers=markers,
        event_vlines=event_vlines,
        event_vline_style=event_vline_style,
        event_vline_order=event_vline_order,
        x_axis=as_optional_ndarray(x_axis),
        target_axis=as_optional_ndarray(target_axis),
        time_start_ms=time_start_ms,
        time_end_ms=time_end_ms,
        time_start_frame=time_start_frame,
        time_end_frame=time_end_frame,
        time_zero_frame=time_zero_frame,
        device_rate=device_rate,
        cop_channels=cop_channels,
        grid_layout=grid_layout,
        cop_style=cop_style or {},
        common_style=common_style or {},
        window_spans=window_spans or [],
    )


def plot_com(
    *,
    aggregated: Dict[str, np.ndarray],
    output_path: Path,
    key: Tuple[Any, ...],
    mode_name: str,
    group_fields: List[str],
    markers: Dict[str, Dict[str, float]],
    event_vlines: List[Dict[str, Any]],
    event_vline_style: Dict[str, Any],
    event_vline_order: Sequence[str],
    x_axis: Optional[np.ndarray],
    time_start_ms: float,
    time_end_ms: float,
    time_start_frame: Optional[float],
    time_end_frame: Optional[float],
    time_zero_frame: float = 0.0,
    device_rate: float = 1000.0,
    com_channels: Sequence[str] = (),
    grid_layout: Optional[Sequence[int]] = None,
    com_style: Optional[Dict[str, Any]] = None,
    common_style: Optional[Dict[str, Any]] = None,
    window_spans: Optional[List[Dict[str, Any]]] = None,
) -> None:
    _common._plot_com(
        aggregated=aggregated,
        output_path=as_output_path(output_path),
        key=as_tuple_key(key),
        mode_name=mode_name,
        group_fields=group_fields,
        markers=markers,
        event_vlines=event_vlines,
        event_vline_style=event_vline_style,
        event_vline_order=event_vline_order,
        x_axis=as_optional_ndarray(x_axis),
        time_start_ms=time_start_ms,
        time_end_ms=time_end_ms,
        time_start_frame=time_start_frame,
        time_end_frame=time_end_frame,
        time_zero_frame=time_zero_frame,
        device_rate=device_rate,
        com_channels=com_channels,
        grid_layout=grid_layout,
        com_style=com_style or {},
        common_style=common_style or {},
        window_spans=window_spans or [],
    )


def plot_cop_overlay(
    *,
    aggregated_by_key: Dict[Tuple[Any, ...], Dict[str, np.ndarray]],
    event_vlines_by_key: Dict[Tuple[Any, ...], List[Dict[str, Any]]],
    pooled_event_vlines: Sequence[Dict[str, Any]],
    event_vline_style: Dict[str, Any],
    event_vline_overlay_cfg: Optional[Dict[str, Any]],
    event_vline_order: Sequence[str],
    output_path: Path,
    mode_name: str,
    group_fields: List[str],
    sorted_keys: List[Tuple[Any, ...]],
    x: np.ndarray,
    window_spans: List[Dict[str, Any]],
    cop_channels: Sequence[str],
    grid_layout: Optional[Sequence[int]],
    cop_style: Dict[str, Any],
    common_style: Dict[str, Any],
    filtered_group_fields: List[str],
    color_by_fields: Optional[List[str]] = None,
    time_start_frame: Optional[float] = None,
    time_end_frame: Optional[float] = None,
    time_zero_frame: float = 0.0,
) -> None:
    _common._plot_cop_overlay(
        aggregated_by_key=aggregated_by_key,
        event_vlines_by_key=event_vlines_by_key,
        pooled_event_vlines=pooled_event_vlines,
        event_vline_style=event_vline_style,
        event_vline_overlay_cfg=event_vline_overlay_cfg,
        event_vline_order=event_vline_order,
        output_path=as_output_path(output_path),
        mode_name=mode_name,
        group_fields=group_fields,
        sorted_keys=as_tuple_keys(sorted_keys),
        x=as_ndarray(x),
        window_spans=window_spans,
        cop_channels=cop_channels,
        grid_layout=grid_layout,
        cop_style=cop_style,
        common_style=common_style,
        filtered_group_fields=filtered_group_fields,
        color_by_fields=color_by_fields,
        time_start_frame=time_start_frame,
        time_end_frame=time_end_frame,
        time_zero_frame=time_zero_frame,
    )


def plot_com_overlay(
    *,
    aggregated_by_key: Dict[Tuple[Any, ...], Dict[str, np.ndarray]],
    event_vlines_by_key: Dict[Tuple[Any, ...], List[Dict[str, Any]]],
    pooled_event_vlines: Sequence[Dict[str, Any]],
    event_vline_style: Dict[str, Any],
    event_vline_overlay_cfg: Optional[Dict[str, Any]],
    event_vline_order: Sequence[str],
    output_path: Path,
    mode_name: str,
    group_fields: List[str],
    sorted_keys: List[Tuple[Any, ...]],
    x: np.ndarray,
    window_spans: List[Dict[str, Any]],
    com_channels: Sequence[str],
    grid_layout: Optional[Sequence[int]],
    com_style: Dict[str, Any],
    common_style: Dict[str, Any],
    filtered_group_fields: List[str],
    color_by_fields: Optional[List[str]] = None,
    time_start_frame: Optional[float] = None,
    time_end_frame: Optional[float] = None,
    time_zero_frame: float = 0.0,
) -> None:
    _common._plot_com_overlay(
        aggregated_by_key=aggregated_by_key,
        event_vlines_by_key=event_vlines_by_key,
        pooled_event_vlines=pooled_event_vlines,
        event_vline_style=event_vline_style,
        event_vline_overlay_cfg=event_vline_overlay_cfg,
        event_vline_order=event_vline_order,
        output_path=as_output_path(output_path),
        mode_name=mode_name,
        group_fields=group_fields,
        sorted_keys=as_tuple_keys(sorted_keys),
        x=as_ndarray(x),
        window_spans=window_spans,
        com_channels=com_channels,
        grid_layout=grid_layout,
        com_style=com_style,
        common_style=common_style,
        filtered_group_fields=filtered_group_fields,
        color_by_fields=color_by_fields,
        time_start_frame=time_start_frame,
        time_end_frame=time_end_frame,
        time_zero_frame=time_zero_frame,
    )


__all__ = [
    "plot_com",
    "plot_com_overlay",
    "plot_cop",
    "plot_cop_overlay",
]
